name: MSBuild

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    env:
      BUILD_PRESET: Win64
      CONFIGURATION: RelWithDebInfo
      INSTALL_CONFIGURATION: ${{ github.workspace }}/out/install
      DLL_OUT: GoWR.Tweaks
    permissions:
      contents: write
      packages: write
      actions: read
      security-events: write
    steps:
      - name: Checkout main repository
        uses: actions/checkout@main
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup environment variables
        run: |
          $cmdOutput = Split-Path -Path $pwd -Leaf
          $branch = "${{ github.ref_name }}"
          $branch = $branch.replace('/','-')
          $_ver = "1.0.$(git rev-list HEAD --count)-$(git git rev-parse --short=8 HEAD)+${{ github.run_number }}-branch-$branch"
          echo "commit_ver=$_ver" >> "$Env:GITHUB_ENV"
          echo "zip_name=$cmdOutput-$_ver" >> "$Env:GITHUB_ENV"
          echo "zip_file=${{ github.workspace }}\$cmdOutput-$_ver.zip" >> "$Env:GITHUB_ENV"
          echo "folder=$cmdOutput" >> "$Env:GITHUB_ENV"
          echo "BUILD_CONFIGURATION=${{ github.workspace }}/out/build/${{ env.BUILD_PRESET }}" >> "$Env:GITHUB_ENV"
          $push = "false"
          $pr = "true"
          $is_pr = "${{ github.event_name }}" -ieq "pull_request"
          if ("${{ github.event_name }}" -ieq "push" -or $is_pr)
          {
              $push = "true"
          }
          if ($is_pr)
          {
